### ISSUE TITLE
Login de la App

### ISSUE THREAD

**Issue by DanielFernandezFdez** [DanielFernandezFdez/GESPRO_Teoria_2022#1]
A través de la identificación con el nombre de usuario y la comprobación de la contraseña se permite el acceso a los usuarios

**Comment by MiguelExtremo** [comment]
Para llevar a cabo el Login de la aplicación llevaremos a cabo dos subtareas como identificar a los usuarios de forma previa 
y comprobar la contraseña introducida para ver si es correcta.
